#----------------- CONSTANTES DE TAGS DE ORIENTAÇÃO---------------#
DESCRICAO_MESTRADO = 'Dissertação de mestrado'
ORIENTADOR_PRINCIPAL = 'ORIENTADOR_PRINCIPAL'
CO_ORIENTADOR = 'CO_ORIENTADOR'
DESCRICAO_DOUTORADO = 'Tese de doutorado'
DESCRICAO_IC1 = "Iniciação Científica"
DESCRICAO_IC2 = "INICIACAO_CIENTIFICA"

#---------------- CONSTANTES DE PESO DO EDITAL (ENSINO) ------------------#
PESO_OP_DOUTORADO_CONCLUIDO = 0 #OP = ORIENTADOR PRINCIPAL
PESO_OP_DOUTORADO_EM_ANDAMENTO = 0
PESO_CO_DOUTORADO_CONCLUIDO = 0 #CO = COORIENTADOR
PESO_CO_DOUTORADO_EM_ANDAMENTO = 0
PESO_OP_MESTRADO_CONCLUIDO = 0
PESO_OP_MESTRADO_EM_ANDAMENTO = 0 
PESO_CO_MESTRADO_CONCLUIDO = 0
PESO_CO_MESTRADO_EM_ANDAMENTO = 0

#----------------- CONSTANTES DE PESO DO EDITAL (PESQUISA) ------------------#
PESO_PUBLICACAO_LIVRO_ISBN = 4
PESO_PUBLICACAO_CAPITULO_ISBN = 2
PESO_PUBLICACAO_TRABALHO_EVENTO = 2
PESO_DEPOSITO_DE_PATENTE = 4
PESO_REGISTRO_DE_PATENTE = 4
ORIENTACAO_EM_IC = 0

QUALIS_A1 = 10
QUALIS_A2 = 8
QUALIS_A3 = 6
QUALIS_A4 = 4
QUALIS_B1 = 2
QUALIS_B2 = 2
QUALIS_B3 = 2
QUALIS_B4 = 0

PESO_TECNICO_ARTISTICO = 0 #qualis = C
PONTUACAO_BOLSISTA = 0