#----------------- CONSTANTES DE TAGS DE ORIENTAÇÃO---------------#
DESCRICAO_MESTRADO = 'Dissertação de mestrado'
ORIENTADOR_PRINCIPAL = 'ORIENTADOR_PRINCIPAL'
CO_ORIENTADOR = 'CO_ORIENTADOR'
DESCRICAO_DOUTORADO = 'Tese de doutorado'
DESCRICAO_IC1 = "Iniciação Científica"
DESCRICAO_IC2 = "INICIACAO_CIENTIFICA"

#---------------- CONSTANTES DE PESO DO EDITAL (ENSINO) ------------------#
PESO_OP_DOUTORADO_CONCLUIDO = 5.21 #OP = ORIENTADOR PRINCIPAL
PESO_OP_DOUTORADO_EM_ANDAMENTO = 4.76
PESO_CO_DOUTORADO_CONCLUIDO = 3.50 #CO = COORIENTADOR
PESO_CO_DOUTORADO_EM_ANDAMENTO = 3.11
PESO_OP_MESTRADO_CONCLUIDO = 3.91
PESO_OP_MESTRADO_EM_ANDAMENTO = 3.46 
PESO_CO_MESTRADO_CONCLUIDO = 2.62
PESO_CO_MESTRADO_EM_ANDAMENTO = 2.23

#----------------- CONSTANTES DE PESO DO EDITAL (PESQUISA) ------------------#
PESO_PUBLICACAO_LIVRO_ISBN = 5.27
PESO_PUBLICACAO_CAPITULO_ISBN = 2.46
PESO_PUBLICACAO_TRABALHO_EVENTO = 1.67
PESO_DEPOSITO_DE_PATENTE = 6.83
PESO_REGISTRO_DE_PATENTE = 11.61
ORIENTACAO_EM_IC = 2.05

QUALIS_A1 = 8.07
QUALIS_A2 = 7.61
QUALIS_A3 = 7.15
QUALIS_A4 = 6.69
QUALIS_B1 = 6.02
QUALIS_B2 = 5.56
QUALIS_B3 = 5.10
QUALIS_B4 = 4.64

PESO_TECNICO_ARTISTICO = 1.02 #qualis = C
PONTUACAO_BOLSISTA = 4.14


