#----------------- CONSTANTES DE TAGS DE ORIENTAÇÃO---------------#
DESCRICAO_MESTRADO = 'Dissertação de mestrado'
ORIENTADOR_PRINCIPAL = 'ORIENTADOR_PRINCIPAL'
CO_ORIENTADOR = 'CO_ORIENTADOR'
DESCRICAO_DOUTORADO = 'Tese de doutorado'
DESCRICAO_IC1 = "Iniciação Científica"
DESCRICAO_IC2 = "INICIACAO_CIENTIFICA"

#---------------- CONSTANTES DE PESO DO EDITAL (ENSINO) ------------------#
PESO_OP_DOUTORADO_CONCLUIDO = 5 #OP = ORIENTADOR PRINCIPAL
PESO_OP_DOUTORADO_EM_ANDAMENTO = 2.5
PESO_CO_DOUTORADO_CONCLUIDO = 5 #CO = COORIENTADOR
PESO_CO_DOUTORADO_EM_ANDAMENTO = 2.5
PESO_OP_MESTRADO_CONCLUIDO = 3
PESO_OP_MESTRADO_EM_ANDAMENTO = 1.5 
PESO_CO_MESTRADO_CONCLUIDO = 3
PESO_CO_MESTRADO_EM_ANDAMENTO = 1.5

#----------------- CONSTANTES DE PESO DO EDITAL (PESQUISA) ------------------#
PESO_PUBLICACAO_LIVRO_ISBN = 0
PESO_PUBLICACAO_CAPITULO_ISBN = 0
PESO_PUBLICACAO_TRABALHO_EVENTO = 0
PESO_DEPOSITO_DE_PATENTE = 5
PESO_REGISTRO_DE_PATENTE = 5
ORIENTACAO_EM_IC = 1

QUALIS_A1 = 4
QUALIS_A2 = 4
QUALIS_A3 = 4
QUALIS_A4 = 4
QUALIS_B1 = 1
QUALIS_B2 = 1
QUALIS_B3 = 1
QUALIS_B4 = 1

PESO_TECNICO_ARTISTICO = 0 #qualis = C
PONTUACAO_BOLSISTA = 0